//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Торговый_центрEntities : DbContext
    {
        public Торговый_центрEntities()
            : base("name=Торговый_центрEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Аренда> Аренда { get; set; }
        public virtual DbSet<Договора> Договора { get; set; }
        public virtual DbSet<Оплата> Оплата { get; set; }
        public virtual DbSet<Участки> Участки { get; set; }
    }
}
