//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аренда
    {
        public int ID_арендатора { get; set; }
        public int Номер_договора { get; set; }
        public string Цель_аренды { get; set; }
        public string Телефон { get; set; }
        public string ФИО { get; set; }
    }
}
