//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата
    {
        public int ID_Оплаты { get; set; }
        public Nullable<System.DateTime> Дата_оплаты { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    }
}
