//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Участки
    {
        public int ID_Арендатора { get; set; }
        public string Магазин { get; set; }
        public Nullable<int> Площадь { get; set; }
        public Nullable<System.DateTime> Дата_начала_аренды { get; set; }
        public Nullable<System.DateTime> Дата_окончания_аренды { get; set; }
        public string Услуги { get; set; }
    }
}
